# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/ubuntu1604"
  config.ssh.insert_key=false
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider:virtualbox do |v|
    v.memory=256
    v.linked_clone=true
  end

  config.vm.define "test_sandbox" do |test_sandbox|
    test_sandbox.vm.hostname="sandbox.test"
    test_sandbox.vm.network:private_network, ip:"192.168.60.4"
  end

end