---
- hosts: multi
  become: true

  tasks:
    - name: Install git
      apt:
        name: "git"
        state: present

    - name: Make sure git is installed and running
      service:
        name: git
        state: started
        enabled: true
