---
- name: Update apt cache if needed
  apt: update_cache=true cache_valid_time=3600

- name: Install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: "u+x,g+x"
