---
- name: Update apt cache if needed
  apt: update_cache=true cache_valid_time=3600

- name: Download and install Java
  apt:
    name: "openjdk-11-jdk"
    state: present

- name: Ensure Java is installed
  shell: java -version
  register: java
